# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../ui/jcpdstools.ui'
#
# Created by: PyQt5 UI code generator 5.12.3
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(610, 775)
        MainWindow.setMinimumSize(QtCore.QSize(0, 750))
        MainWindow.setMaximumSize(QtCore.QSize(955, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("font: 12pt \"Helvetica\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.splitter.setLineWidth(0)
        self.splitter.setMidLineWidth(0)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setOpaqueResize(True)
        self.splitter.setHandleWidth(7)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.frame_5 = QtWidgets.QFrame(self.splitter)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.tabWidget = QtWidgets.QTabWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(400, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 200))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(20, 20))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_Editor = QtWidgets.QWidget()
        self.tab_Editor.setObjectName("tab_Editor")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_Editor)
        self.verticalLayout_7.setContentsMargins(12, -1, 12, 12)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_Editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName("groupBox_7")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_7)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_SourceFile = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_SourceFile.setReadOnly(True)
        self.lineEdit_SourceFile.setObjectName("lineEdit_SourceFile")
        self.verticalLayout.addWidget(self.lineEdit_SourceFile)
        self.verticalLayout_7.addWidget(self.groupBox_7)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_Editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_ImportCIF = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_ImportCIF.sizePolicy().hasHeightForWidth())
        self.pushButton_ImportCIF.setSizePolicy(sizePolicy)
        self.pushButton_ImportCIF.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButton_ImportCIF.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_ImportCIF.setObjectName("pushButton_ImportCIF")
        self.horizontalLayout_2.addWidget(self.pushButton_ImportCIF)
        self.pushButton_ImportJCPDS = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_ImportJCPDS.setObjectName("pushButton_ImportJCPDS")
        self.horizontalLayout_2.addWidget(self.pushButton_ImportJCPDS)
        self.pushButton_ViewInputFile = QtWidgets.QPushButton(self.groupBox_4)
        self.pushButton_ViewInputFile.setObjectName("pushButton_ViewInputFile")
        self.horizontalLayout_2.addWidget(self.pushButton_ViewInputFile)
        self.verticalLayout_7.addWidget(self.groupBox_4)
        self.groupBox_28 = QtWidgets.QGroupBox(self.tab_Editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_28.sizePolicy().hasHeightForWidth())
        self.groupBox_28.setSizePolicy(sizePolicy)
        self.groupBox_28.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_28.setFlat(True)
        self.groupBox_28.setObjectName("groupBox_28")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_28)
        self.gridLayout.setContentsMargins(12, 12, 12, 12)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox_28)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.doubleSpinBox_CellParamBeta = QtWidgets.QDoubleSpinBox(self.groupBox_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_CellParamBeta.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_CellParamBeta.setSizePolicy(sizePolicy)
        self.doubleSpinBox_CellParamBeta.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_CellParamBeta.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CellParamBeta.setMaximum(360.0)
        self.doubleSpinBox_CellParamBeta.setSingleStep(0.0)
        self.doubleSpinBox_CellParamBeta.setProperty("value", 90.0)
        self.doubleSpinBox_CellParamBeta.setObjectName("doubleSpinBox_CellParamBeta")
        self.gridLayout.addWidget(self.doubleSpinBox_CellParamBeta, 4, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_28)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_28)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.doubleSpinBox_CellParamC = QtWidgets.QDoubleSpinBox(self.groupBox_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_CellParamC.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_CellParamC.setSizePolicy(sizePolicy)
        self.doubleSpinBox_CellParamC.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_CellParamC.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CellParamC.setDecimals(4)
        self.doubleSpinBox_CellParamC.setSingleStep(0.0001)
        self.doubleSpinBox_CellParamC.setProperty("value", 1.0)
        self.doubleSpinBox_CellParamC.setObjectName("doubleSpinBox_CellParamC")
        self.gridLayout.addWidget(self.doubleSpinBox_CellParamC, 0, 7, 1, 1)
        self.doubleSpinBox_CellParamA = QtWidgets.QDoubleSpinBox(self.groupBox_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_CellParamA.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_CellParamA.setSizePolicy(sizePolicy)
        self.doubleSpinBox_CellParamA.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_CellParamA.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CellParamA.setDecimals(4)
        self.doubleSpinBox_CellParamA.setSingleStep(0.001)
        self.doubleSpinBox_CellParamA.setProperty("value", 1.0)
        self.doubleSpinBox_CellParamA.setObjectName("doubleSpinBox_CellParamA")
        self.gridLayout.addWidget(self.doubleSpinBox_CellParamA, 0, 1, 1, 1)
        self.doubleSpinBox_CellParamB = QtWidgets.QDoubleSpinBox(self.groupBox_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_CellParamB.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_CellParamB.setSizePolicy(sizePolicy)
        self.doubleSpinBox_CellParamB.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_CellParamB.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CellParamB.setDecimals(4)
        self.doubleSpinBox_CellParamB.setSingleStep(0.0001)
        self.doubleSpinBox_CellParamB.setProperty("value", 1.0)
        self.doubleSpinBox_CellParamB.setObjectName("doubleSpinBox_CellParamB")
        self.gridLayout.addWidget(self.doubleSpinBox_CellParamB, 0, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_28)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 6, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_28)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 3, 1, 1)
        self.doubleSpinBox_CellParamGamma = QtWidgets.QDoubleSpinBox(self.groupBox_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_CellParamGamma.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_CellParamGamma.setSizePolicy(sizePolicy)
        self.doubleSpinBox_CellParamGamma.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_CellParamGamma.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CellParamGamma.setMaximum(360.0)
        self.doubleSpinBox_CellParamGamma.setSingleStep(0.01)
        self.doubleSpinBox_CellParamGamma.setProperty("value", 90.0)
        self.doubleSpinBox_CellParamGamma.setObjectName("doubleSpinBox_CellParamGamma")
        self.gridLayout.addWidget(self.doubleSpinBox_CellParamGamma, 4, 7, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_28)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 4, 6, 1, 1)
        self.doubleSpinBox_CellParamAlpha = QtWidgets.QDoubleSpinBox(self.groupBox_28)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_CellParamAlpha.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_CellParamAlpha.setSizePolicy(sizePolicy)
        self.doubleSpinBox_CellParamAlpha.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_CellParamAlpha.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_CellParamAlpha.setDecimals(2)
        self.doubleSpinBox_CellParamAlpha.setMaximum(360.0)
        self.doubleSpinBox_CellParamAlpha.setSingleStep(0.01)
        self.doubleSpinBox_CellParamAlpha.setProperty("value", 90.0)
        self.doubleSpinBox_CellParamAlpha.setObjectName("doubleSpinBox_CellParamAlpha")
        self.gridLayout.addWidget(self.doubleSpinBox_CellParamAlpha, 4, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_28)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_Editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.groupBox_6)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.lineEdit_CrystalSystem = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_CrystalSystem.setMinimumSize(QtCore.QSize(80, 0))
        self.lineEdit_CrystalSystem.setReadOnly(True)
        self.lineEdit_CrystalSystem.setObjectName("lineEdit_CrystalSystem")
        self.horizontalLayout_5.addWidget(self.lineEdit_CrystalSystem)
        self.label_14 = QtWidgets.QLabel(self.groupBox_6)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.lineEdit_SpaceGroup = QtWidgets.QLineEdit(self.groupBox_6)
        self.lineEdit_SpaceGroup.setReadOnly(True)
        self.lineEdit_SpaceGroup.setObjectName("lineEdit_SpaceGroup")
        self.horizontalLayout_5.addWidget(self.lineEdit_SpaceGroup)
        self.verticalLayout_7.addWidget(self.groupBox_6)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_Editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_8.setContentsMargins(12, -1, 12, 12)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.doubleSpinBox_K0p = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_K0p.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_K0p.setSizePolicy(sizePolicy)
        self.doubleSpinBox_K0p.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_K0p.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_K0p.setMaximum(10.0)
        self.doubleSpinBox_K0p.setSingleStep(0.1)
        self.doubleSpinBox_K0p.setProperty("value", 4.0)
        self.doubleSpinBox_K0p.setObjectName("doubleSpinBox_K0p")
        self.gridLayout_8.addWidget(self.doubleSpinBox_K0p, 2, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_8.addWidget(self.label_17, 2, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_8.addWidget(self.label_21, 2, 4, 1, 1)
        self.doubleSpinBox_K0 = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_K0.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_K0.setSizePolicy(sizePolicy)
        self.doubleSpinBox_K0.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_K0.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_K0.setMaximum(1000.0)
        self.doubleSpinBox_K0.setSingleStep(1.0)
        self.doubleSpinBox_K0.setProperty("value", 200.0)
        self.doubleSpinBox_K0.setObjectName("doubleSpinBox_K0")
        self.gridLayout_8.addWidget(self.doubleSpinBox_K0, 2, 1, 1, 1)
        self.doubleSpinBox_ThermExpan = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_ThermExpan.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_ThermExpan.setSizePolicy(sizePolicy)
        self.doubleSpinBox_ThermExpan.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_ThermExpan.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_ThermExpan.setDecimals(5)
        self.doubleSpinBox_ThermExpan.setMaximum(1.0)
        self.doubleSpinBox_ThermExpan.setSingleStep(1e-05)
        self.doubleSpinBox_ThermExpan.setProperty("value", 1e-05)
        self.doubleSpinBox_ThermExpan.setObjectName("doubleSpinBox_ThermExpan")
        self.gridLayout_8.addWidget(self.doubleSpinBox_ThermExpan, 2, 5, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_8.addWidget(self.label_16, 2, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.groupBox_2)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_Editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setFlat(True)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_5)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEdit_Comment = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_Comment.setObjectName("lineEdit_Comment")
        self.horizontalLayout_4.addWidget(self.lineEdit_Comment)
        self.verticalLayout_7.addWidget(self.groupBox_5)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_Editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout.addWidget(self.label_24)
        self.doubleSpinBox_MinDsp = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_MinDsp.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_MinDsp.setSizePolicy(sizePolicy)
        self.doubleSpinBox_MinDsp.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_MinDsp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_MinDsp.setMinimum(0.1)
        self.doubleSpinBox_MinDsp.setSingleStep(0.01)
        self.doubleSpinBox_MinDsp.setProperty("value", 0.8)
        self.doubleSpinBox_MinDsp.setObjectName("doubleSpinBox_MinDsp")
        self.horizontalLayout.addWidget(self.doubleSpinBox_MinDsp)
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout.addWidget(self.label_20)
        self.doubleSpinBox_MinInt = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doubleSpinBox_MinInt.sizePolicy().hasHeightForWidth())
        self.doubleSpinBox_MinInt.setSizePolicy(sizePolicy)
        self.doubleSpinBox_MinInt.setMinimumSize(QtCore.QSize(80, 0))
        self.doubleSpinBox_MinInt.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.doubleSpinBox_MinInt.setProperty("value", 1.0)
        self.doubleSpinBox_MinInt.setObjectName("doubleSpinBox_MinInt")
        self.horizontalLayout.addWidget(self.doubleSpinBox_MinInt)
        self.verticalLayout_7.addWidget(self.groupBox_3)
        self.groupBox = QtWidgets.QGroupBox(self.tab_Editor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setContentsMargins(12, 12, 12, 12)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_CalculateJCPDS = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_CalculateJCPDS.setObjectName("pushButton_CalculateJCPDS")
        self.horizontalLayout_3.addWidget(self.pushButton_CalculateJCPDS)
        self.pushButton_WriteJCPDS = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_WriteJCPDS.setObjectName("pushButton_WriteJCPDS")
        self.horizontalLayout_3.addWidget(self.pushButton_WriteJCPDS)
        self.verticalLayout_7.addWidget(self.groupBox)
        self.tabWidget.addTab(self.tab_Editor, "")
        self.tab_About = QtWidgets.QWidget()
        self.tab_About.setObjectName("tab_About")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_About)
        self.verticalLayout_2.setContentsMargins(3, 12, 3, 12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_26 = QtWidgets.QFrame(self.tab_About)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_26.sizePolicy().hasHeightForWidth())
        self.frame_26.setSizePolicy(sizePolicy)
        self.frame_26.setObjectName("frame_26")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_26)
        self.gridLayout_13.setContentsMargins(-1, 3, -1, 3)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.verticalLayout_2.addWidget(self.frame_26)
        self.textEdit_2 = QtWidgets.QTextEdit(self.tab_About)
        self.textEdit_2.setReadOnly(True)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_2.addWidget(self.textEdit_2)
        self.frame_27 = QtWidgets.QFrame(self.tab_About)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_27.sizePolicy().hasHeightForWidth())
        self.frame_27.setSizePolicy(sizePolicy)
        self.frame_27.setObjectName("frame_27")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.frame_27)
        self.gridLayout_12.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.verticalLayout_2.addWidget(self.frame_27)
        self.tabWidget.addTab(self.tab_About, "")
        self.verticalLayout_9.addWidget(self.tabWidget)
        self.verticalLayout_25.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.mplactionOpen = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.mplactionOpen.setFont(font)
        self.mplactionOpen.setObjectName("mplactionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.actionClose.setFont(font)
        self.actionClose.setObjectName("actionClose")
        self.mplactionSave_background = QtWidgets.QAction(MainWindow)
        self.mplactionSave_background.setObjectName("mplactionSave_background")
        self.mplactionSave_background_subtracted = QtWidgets.QAction(MainWindow)
        self.mplactionSave_background_subtracted.setObjectName("mplactionSave_background_subtracted")
        self.actionSet_range = QtWidgets.QAction(MainWindow)
        self.actionSet_range.setObjectName("actionSet_range")
        self.actionY_Scale = QtWidgets.QAction(MainWindow)
        self.actionY_Scale.setObjectName("actionY_Scale")
        self.mplactionPrint = QtWidgets.QAction(MainWindow)
        self.mplactionPrint.setObjectName("mplactionPrint")
        self.actionBackground_parameters = QtWidgets.QAction(MainWindow)
        self.actionBackground_parameters.setObjectName("actionBackground_parameters")
        self.mplactionNew_JList = QtWidgets.QAction(MainWindow)
        self.mplactionNew_JList.setObjectName("mplactionNew_JList")
        self.mplactionLoad_Jlist = QtWidgets.QAction(MainWindow)
        self.mplactionLoad_Jlist.setObjectName("mplactionLoad_Jlist")
        self.mplactionSave_JList = QtWidgets.QAction(MainWindow)
        self.mplactionSave_JList.setObjectName("mplactionSave_JList")
        self.mplactionEdit_JList = QtWidgets.QAction(MainWindow)
        self.mplactionEdit_JList.setObjectName("mplactionEdit_JList")
        self.mplactionShow_a_JCPDS_card = QtWidgets.QAction(MainWindow)
        self.mplactionShow_a_JCPDS_card.setObjectName("mplactionShow_a_JCPDS_card")
        self.mplactionXray_wavelength = QtWidgets.QAction(MainWindow)
        self.mplactionXray_wavelength.setObjectName("mplactionXray_wavelength")
        self.mplactionShow_Unshow_JList = QtWidgets.QAction(MainWindow)
        self.mplactionShow_Unshow_JList.setObjectName("mplactionShow_Unshow_JList")
        self.mplactionShow_a_JCPDS_file = QtWidgets.QAction(MainWindow)
        self.mplactionShow_a_JCPDS_file.setObjectName("mplactionShow_a_JCPDS_file")
        self.actionCiting_PeakPo = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.actionCiting_PeakPo.setFont(font)
        self.actionCiting_PeakPo.setObjectName("actionCiting_PeakPo")
        self.actionShortcut_keys = QtWidgets.QAction(MainWindow)
        self.actionShortcut_keys.setObjectName("actionShortcut_keys")

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "JCPDSTools"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Source file"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Step1"))
        self.pushButton_ImportCIF.setToolTip(_translate("MainWindow", "Open the first CHI file"))
        self.pushButton_ImportCIF.setText(_translate("MainWindow", "Import CIF"))
        self.pushButton_ImportJCPDS.setText(_translate("MainWindow", "Import JCPDS"))
        self.pushButton_ViewInputFile.setText(_translate("MainWindow", "View file"))
        self.groupBox_28.setTitle(_translate("MainWindow", "Step2"))
        self.label_2.setText(_translate("MainWindow", "b (A)"))
        self.label.setText(_translate("MainWindow", "a (A)"))
        self.label_5.setText(_translate("MainWindow", "alpha (deg)"))
        self.label_4.setText(_translate("MainWindow", "c (A)"))
        self.label_6.setText(_translate("MainWindow", "beta (deg)"))
        self.label_12.setText(_translate("MainWindow", "gamma (deg)"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Symmetry"))
        self.label_13.setText(_translate("MainWindow", "Crystal system"))
        self.label_14.setText(_translate("MainWindow", "Space group"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Step3"))
        self.label_17.setText(_translate("MainWindow", "K0p"))
        self.label_21.setText(_translate("MainWindow", "Therm. Expans."))
        self.label_16.setText(_translate("MainWindow", "K0"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Step4"))
        self.label_3.setText(_translate("MainWindow", "Comment"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Step5 (see help tap for the parameters)"))
        self.label_24.setText(_translate("MainWindow", "Min. dsp"))
        self.label_20.setText(_translate("MainWindow", "Min. Int"))
        self.groupBox.setTitle(_translate("MainWindow", "Step6"))
        self.pushButton_CalculateJCPDS.setText(_translate("MainWindow", "Calculate"))
        self.pushButton_WriteJCPDS.setToolTip(_translate("MainWindow", "Set pressure to 1 bar"))
        self.pushButton_WriteJCPDS.setText(_translate("MainWindow", "Write"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_Editor), _translate("MainWindow", "Editor"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">JCPDSTools</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">by S.-H. Dan Shim (SHDShim@gmail.com)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2020</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">This tool allows for (1) converting an existing CIF to a JCPDS file, (2) edit an exiting JCPDS file, and (3) check possible problems in JCPDS file.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(Tips)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you do not have a CIF or a JCPDS for your material, you can first find a CIF or JCPDS for an analog material (for example different composition but the same crystal structure) and edit the unit-cell parameters and thermoelastic parameters.  Note that in this case, the calculatd intensities may not be accurate for your composition.  Yet, the peak position would be still accurate.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Min. Int. defines the minimum peak intensity to include in JCPDS after calculation.  If this value is too low (&lt;1%), it will slow down PeakPo.  However, if you need to identify weak lines, it is necessary to set this to low.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Min. dsp defines the minimum d-spacing to include in JCPDS after calculation.  If this value is too low (&lt;0.8 A), it will slow down PeakPo.  However, if you have high angle diffraction lines to identify, it is ncessary to set this small.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">If you download a CIF file from MaterialsProject.org, make sure you download `Symmetrized` CIFs.  Others are all in P1 symmetry and would not work correctly.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">----------------------------</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">JCDPS file format</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">----------------------------</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">line 1: version_number</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">line 2: header</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">line 3: symmetry_code, K0, K0p</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">line 4: a, b, c, alpha, beta, gamma (this line is different depending on symmetry, see examples)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">line 5: thermal expansion parameter</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">line 6: column description (d  I/I0  h k l)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">line 7: d-spacing, I/I0, h, k, l</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">-----------------------------</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* symmetry code</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1    cubic</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2    hexagonal</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3    tetragonal</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4    orthorhombic</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">5    monoclinic</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">6    triclinic</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">7    No symmetry</p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_About), _translate("MainWindow", "Help"))
        self.mplactionOpen.setText(_translate("MainWindow", "Open CHI file"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.mplactionSave_background.setText(_translate("MainWindow", "Save background"))
        self.mplactionSave_background_subtracted.setText(_translate("MainWindow", "Save background subtracted"))
        self.actionSet_range.setText(_translate("MainWindow", "Set range"))
        self.actionY_Scale.setText(_translate("MainWindow", "Y Scale (Lin/Log)"))
        self.mplactionPrint.setText(_translate("MainWindow", "Print"))
        self.actionBackground_parameters.setText(_translate("MainWindow", "Background parameters"))
        self.mplactionNew_JList.setText(_translate("MainWindow", "New JList"))
        self.mplactionLoad_Jlist.setText(_translate("MainWindow", "Load JList"))
        self.mplactionSave_JList.setText(_translate("MainWindow", "Save JList"))
        self.mplactionEdit_JList.setText(_translate("MainWindow", "Edit JList"))
        self.mplactionShow_a_JCPDS_card.setText(_translate("MainWindow", "Show a JCPDS card"))
        self.mplactionXray_wavelength.setText(_translate("MainWindow", "X-ray wavelength"))
        self.mplactionShow_Unshow_JList.setText(_translate("MainWindow", "Show/Unshow JList"))
        self.mplactionShow_a_JCPDS_file.setText(_translate("MainWindow", "Show a JCPDS file"))
        self.actionCiting_PeakPo.setText(_translate("MainWindow", "Citing PeakPo"))
        self.actionShortcut_keys.setText(_translate("MainWindow", "Shortcut keys"))
